### PR TITLE
Added explanation of work unit registration process to README

### PR DESCRIPTION
**Pull request by cb372**
I've added a bit of documentation about:
- how to supply a cluster with work units
- how to peg a work unit to a node

This is all information gleaned from experimentation and reading the source, so let me know if any of it is incorrect.

### CODE REVIEW

**Comment by eric** [comment]
This would definitely be helpful info to have in the README.

**Comment by jdanbrown** [comment]
+1 This wasn't apparent to me, either. Had to read the source and experiment to figure it out.

**Comment by eribeiro** [comment]
+1 for this change.

**Comment by cscotta** [comment]
Hey Chris, this is fantastic. Sorry to have missed this pull request. Great documentation, and impeccably written. Really appreciate it.

– Scott

**Pull request merged**
